apiVersion: v1alpha1
kind: Role
metadata:
  name: role-template-link-submit-next-anonymous
  labels:
    halo.run/hidden: "true"
    halo.run/role-template: "true"
    rbac.authorization.halo.run/aggregate-to-anonymous: "true"
  annotations:
    rbac.authorization.halo.run/module: "PluginLinkSubmitAnonymous"
    rbac.authorization.halo.run/display-name: "PluginLinkSubmit Anonymous AccessRole"
rules:
  - apiGroups: [ "api.link.submit.halo.run" ]
    resources: [ "configuration", "linkgroups", "site-info" ]
    verbs: [ "get", "list" ]
  - apiGroups: [ "api.link.submit.halo.run" ]
    resources: [ "linksubmits", "linksubmits/submit" ]
    verbs: [ "create" ]
  - nonResourceURLs:
      - "/apis/api.link.submit.halo.run/v1alpha1/linkgroups"
      - "/apis/api.link.submit.halo.run/v1alpha1/configuration"
      - "/apis/api.link.submit.halo.run/v1alpha1/site-info"
    verbs: [ "get" ]
  - nonResourceURLs:
      - "/apis/api.link.submit.halo.run/v1alpha1/linksubmits/-/submit"
    verbs: [ "post" ]


---

apiVersion: v1alpha1
kind: Role
metadata:
  name: role-template-link-submit-next-view
  labels:
    halo.run/role-template: "true"
  annotations:
    rbac.authorization.halo.run/module: "友链自助提交"
    rbac.authorization.halo.run/display-name: "友链自助提交查看"
    rbac.authorization.halo.run/ui-permissions: |
      ["plugin:link:submit-next:view"]
rules:
  - apiGroups: [ "link.submit.halo.run" ]
    resources: [ "linksubmits","cronlinksubmits" ]
    verbs: [ "get", "list" ]
  - apiGroups: [ "console.api.link.submit.halo.run" ]
    resources: [ "linksubmits"]
    verbs: [ "get", "list" ]

---

apiVersion: v1alpha1
kind: Role
metadata:
  name: role-template-link-submit-next-manage
  labels:
    halo.run/role-template: "true"
  annotations:
    rbac.authorization.halo.run/module: "友链自助提交"
    rbac.authorization.halo.run/display-name: "友链自助提交管理"
    rbac.authorization.halo.run/ui-permissions: |
      ["plugin:link:submit-next:manage"]
    rbac.authorization.halo.run/dependencies: |
      ["role-template-link-submit-next-view"]
rules:
  - apiGroups: [ "link.submit.halo.run" ]
    resources: [ "linksubmits","cronlinksubmits" ]
    verbs: [ "create", "patch", "update", "delete", "deletecollection" ]
  - apiGroups: [ "console.api.link.submit.halo.run" ]
    resources: [ "linksubmits/check" ]
    verbs: [ "create", "patch", "update", "delete", "deletecollection" ]
