apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  name: link-submit-next
  annotations:
    "store.halo.run/app-id": "app-link-submit-next"
spec:
  enabled: false
  requires: ">=2.25.0"
  pluginDependencies:
    "PluginLinks": ">=2.0.0"
  version: "1.0.11"
  author:
    name: chenhufei
    website: https://github.com/chenhufei
  logo: logo.svg
  homepage: https://github.com/chenhufei/plugin-link-submit-next
  repo: https://github.com/chenhufei/plugin-link-submit-next
  issues: https://github.com/chenhufei/plugin-link-submit-next/issues
  configMapName: link-submit-next-configmap
  settingName: link-submit-next-settings
  displayName: "友链自助提交 Next"
  description: "访问者可以自助提交友链，并在后台管理页面进行审核。"
  license:
    - name: "GPL-3.0"
      url: "https://www.gnu.org/licenses/gpl-3.0.html"
